"""citas, clientes, pedidos

Revision ID: cfcefe4475b9
Revises: 
Create Date: 2026-08-04 16:30:36.088493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfcefe4475b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('servicio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profesional_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cliente_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_profesional_id'), 'citas', ['profesional_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('servicio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_lineas_pedido_id'), 'pedido_lineas', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_lineas_pedido_id'), table_name='pedido_lineas')
    op.drop_table('pedido_lineas')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_citas_profesional_id'), table_name='citas')
    op.drop_table('citas')
    # ### end Alembic commands ###
